// Code generated by root alias generator; DO NOT EDIT.
package kugou

import "github.com/rushingrain/kugou-music-api/sdk"

// Primary route aliases expose the shared endpoint constants from the root package.
const (
	PersonalRadioHeart           = sdk.PersonalRadioHeart
	PersonalRadioNew             = sdk.PersonalRadioNew
	PersonalRadioNiche           = sdk.PersonalRadioNiche
	RouteAiRecommend             = sdk.RouteAiRecommend
	RouteAlbum                   = sdk.RouteAlbum
	RouteAlbumDetail             = sdk.RouteAlbumDetail
	RouteAlbumShop               = sdk.RouteAlbumShop
	RouteAlbumSongs              = sdk.RouteAlbumSongs
	RouteArtistAlbums            = sdk.RouteArtistAlbums
	RouteArtistAudios            = sdk.RouteArtistAudios
	RouteArtistDetail            = sdk.RouteArtistDetail
	RouteArtistFollow            = sdk.RouteArtistFollow
	RouteArtistFollowNewsongs    = sdk.RouteArtistFollowNewsongs
	RouteArtistHonour            = sdk.RouteArtistHonour
	RouteArtistLists             = sdk.RouteArtistLists
	RouteArtistUnfollow          = sdk.RouteArtistUnfollow
	RouteArtistVideos            = sdk.RouteArtistVideos
	RouteAudio                   = sdk.RouteAudio
	RouteAudioAccompanyMatching  = sdk.RouteAudioAccompanyMatching
	RouteAudioKtvTotal           = sdk.RouteAudioKtvTotal
	RouteAudioRelated            = sdk.RouteAudioRelated
	RouteBrush                   = sdk.RouteBrush
	RouteCaptchaSent             = sdk.RouteCaptchaSent
	RouteCommentAlbum            = sdk.RouteCommentAlbum
	RouteCommentCount            = sdk.RouteCommentCount
	RouteCommentFloor            = sdk.RouteCommentFloor
	RouteCommentMusic            = sdk.RouteCommentMusic
	RouteCommentMusicClassify    = sdk.RouteCommentMusicClassify
	RouteCommentMusicHotword     = sdk.RouteCommentMusicHotword
	RouteCommentPlaylist         = sdk.RouteCommentPlaylist
	RouteEverydayFriend          = sdk.RouteEverydayFriend
	RouteEverydayHistory         = sdk.RouteEverydayHistory
	RouteEverydayRecommend       = sdk.RouteEverydayRecommend
	RouteEverydayStyleRecommend  = sdk.RouteEverydayStyleRecommend
	RouteFavoriteCount           = sdk.RouteFavoriteCount
	RouteFmClass                 = sdk.RouteFmClass
	RouteFmImage                 = sdk.RouteFmImage
	RouteFmRecommend             = sdk.RouteFmRecommend
	RouteFmSongs                 = sdk.RouteFmSongs
	RouteImages                  = sdk.RouteImages
	RouteImagesAudio             = sdk.RouteImagesAudio
	RouteIp                      = sdk.RouteIp
	RouteIpDateil                = sdk.RouteIpDateil
	RouteIpPlaylist              = sdk.RouteIpPlaylist
	RouteIpZone                  = sdk.RouteIpZone
	RouteIpZoneHome              = sdk.RouteIpZoneHome
	RouteKmrAudioMv              = sdk.RouteKmrAudioMv
	RouteKrmAudio                = sdk.RouteKrmAudio
	RouteLastestSongsListen      = sdk.RouteLastestSongsListen
	RouteLogin                   = sdk.RouteLogin
	RouteLoginCellphone          = sdk.RouteLoginCellphone
	RouteLoginDevice             = sdk.RouteLoginDevice
	RouteLoginOpenplat           = sdk.RouteLoginOpenplat
	RouteLoginQrCheck            = sdk.RouteLoginQrCheck
	RouteLoginQrCreate           = sdk.RouteLoginQrCreate
	RouteLoginQrKey              = sdk.RouteLoginQrKey
	RouteLoginToken              = sdk.RouteLoginToken
	RouteLoginWxCheck            = sdk.RouteLoginWxCheck
	RouteLoginWxCreate           = sdk.RouteLoginWxCreate
	RouteLongaudioAlbumAudios    = sdk.RouteLongaudioAlbumAudios
	RouteLongaudioAlbumDetail    = sdk.RouteLongaudioAlbumDetail
	RouteLongaudioDailyRecommend = sdk.RouteLongaudioDailyRecommend
	RouteLongaudioRankRecommend  = sdk.RouteLongaudioRankRecommend
	RouteLongaudioVipRecommend   = sdk.RouteLongaudioVipRecommend
	RouteLongaudioWeekRecommend  = sdk.RouteLongaudioWeekRecommend
	RouteLyric                   = sdk.RouteLyric
	RoutePcDiantai               = sdk.RoutePcDiantai
	RoutePersonalFm              = sdk.RoutePersonalFm
	RoutePlayhistoryUpload       = sdk.RoutePlayhistoryUpload
	RoutePlaylistAdd             = sdk.RoutePlaylistAdd
	RoutePlaylistDel             = sdk.RoutePlaylistDel
	RoutePlaylistDetail          = sdk.RoutePlaylistDetail
	RoutePlaylistEffect          = sdk.RoutePlaylistEffect
	RoutePlaylistSimilar         = sdk.RoutePlaylistSimilar
	RoutePlaylistTags            = sdk.RoutePlaylistTags
	RoutePlaylistTrackAll        = sdk.RoutePlaylistTrackAll
	RoutePlaylistTrackAllNew     = sdk.RoutePlaylistTrackAllNew
	RoutePlaylistTracksAdd       = sdk.RoutePlaylistTracksAdd
	RoutePlaylistTracksDel       = sdk.RoutePlaylistTracksDel
)
