// Code generated by root alias generator; DO NOT EDIT.
package kugou

import "github.com/rushingrain/kugou-music-api/sdk"

// APIList re-exports the generated endpoint catalog from the SDK package.
var (
	APIList = sdk.APIList
)
