// Code generated by root alias generator; DO NOT EDIT.
package kugou

import "github.com/rushingrain/kugou-music-api/sdk"

// Secondary route aliases cover the remaining user and youth endpoint constants.
const (
	RoutePrivilegeLite          = sdk.RoutePrivilegeLite
	RouteRankAudio              = sdk.RouteRankAudio
	RouteRankInfo               = sdk.RouteRankInfo
	RouteRankList               = sdk.RouteRankList
	RouteRankTop                = sdk.RouteRankTop
	RouteRankVol                = sdk.RouteRankVol
	RouteRecommendSongs         = sdk.RouteRecommendSongs
	RouteRegisterDev            = sdk.RouteRegisterDev
	RouteSceneAudioList         = sdk.RouteSceneAudioList
	RouteSceneCollectionList    = sdk.RouteSceneCollectionList
	RouteSceneLists             = sdk.RouteSceneLists
	RouteSceneListsV2           = sdk.RouteSceneListsV2
	RouteSceneModule            = sdk.RouteSceneModule
	RouteSceneModuleInfo        = sdk.RouteSceneModuleInfo
	RouteSceneMusic             = sdk.RouteSceneMusic
	RouteSceneVideoList         = sdk.RouteSceneVideoList
	RouteSearch                 = sdk.RouteSearch
	RouteSearchComplex          = sdk.RouteSearchComplex
	RouteSearchDefault          = sdk.RouteSearchDefault
	RouteSearchHot              = sdk.RouteSearchHot
	RouteSearchLyric            = sdk.RouteSearchLyric
	RouteSearchMixed            = sdk.RouteSearchMixed
	RouteSearchSuggest          = sdk.RouteSearchSuggest
	RouteServerNow              = sdk.RouteServerNow
	RouteSheetCollection        = sdk.RouteSheetCollection
	RouteSheetCollectionDetail  = sdk.RouteSheetCollectionDetail
	RouteSheetDetail            = sdk.RouteSheetDetail
	RouteSheetHot               = sdk.RouteSheetHot
	RouteSheetList              = sdk.RouteSheetList
	RouteSingerList             = sdk.RouteSingerList
	RouteSongClimax             = sdk.RouteSongClimax
	RouteSongRanking            = sdk.RouteSongRanking
	RouteSongRankingFilter      = sdk.RouteSongRankingFilter
	RouteSongUrl                = sdk.RouteSongUrl
	RouteSongUrlNew             = sdk.RouteSongUrlNew
	RouteThemeMusic             = sdk.RouteThemeMusic
	RouteThemeMusicDetail       = sdk.RouteThemeMusicDetail
	RouteThemePlaylist          = sdk.RouteThemePlaylist
	RouteThemePlaylistTrack     = sdk.RouteThemePlaylistTrack
	RouteTopAlbum               = sdk.RouteTopAlbum
	RouteTopCard                = sdk.RouteTopCard
	RouteTopCardYouth           = sdk.RouteTopCardYouth
	RouteTopIp                  = sdk.RouteTopIp
	RouteTopPlaylist            = sdk.RouteTopPlaylist
	RouteTopSong                = sdk.RouteTopSong
	RouteUserCloud              = sdk.RouteUserCloud
	RouteUserCloudUrl           = sdk.RouteUserCloudUrl
	RouteUserDetail             = sdk.RouteUserDetail
	RouteUserFollow             = sdk.RouteUserFollow
	RouteUserHistory            = sdk.RouteUserHistory
	RouteUserListen             = sdk.RouteUserListen
	RouteUserPlaylist           = sdk.RouteUserPlaylist
	RouteUserVideoCollect       = sdk.RouteUserVideoCollect
	RouteUserVideoLove          = sdk.RouteUserVideoLove
	RouteUserVipDetail          = sdk.RouteUserVipDetail
	RouteVideoDetail            = sdk.RouteVideoDetail
	RouteVideoPrivilege         = sdk.RouteVideoPrivilege
	RouteVideoUrl               = sdk.RouteVideoUrl
	RouteYouthChannelAll        = sdk.RouteYouthChannelAll
	RouteYouthChannelAmway      = sdk.RouteYouthChannelAmway
	RouteYouthChannelDetail     = sdk.RouteYouthChannelDetail
	RouteYouthChannelSimilar    = sdk.RouteYouthChannelSimilar
	RouteYouthChannelSong       = sdk.RouteYouthChannelSong
	RouteYouthChannelSongDetail = sdk.RouteYouthChannelSongDetail
	RouteYouthChannelSub        = sdk.RouteYouthChannelSub
	RouteYouthDayVip            = sdk.RouteYouthDayVip
	RouteYouthDayVipUpgrade     = sdk.RouteYouthDayVipUpgrade
	RouteYouthDynamic           = sdk.RouteYouthDynamic
	RouteYouthDynamicRecent     = sdk.RouteYouthDynamicRecent
	RouteYouthListenSong        = sdk.RouteYouthListenSong
	RouteYouthMonthVipRecord    = sdk.RouteYouthMonthVipRecord
	RouteYouthUnionVip          = sdk.RouteYouthUnionVip
	RouteYouthUserSong          = sdk.RouteYouthUserSong
	RouteYouthVip               = sdk.RouteYouthVip
	RouteYueku                  = sdk.RouteYueku
	RouteYuekuBanner            = sdk.RouteYuekuBanner
	RouteYuekuFm                = sdk.RouteYuekuFm
)
