// Code generated by tools/gen; DO NOT EDIT.
package sdk

import "context"

// Search, sheet, and song ranking models stay together.
type SearchRequest struct {
	Keywords string            `json:"keywords,omitempty"`
	Page     int               `json:"page,omitempty"`
	Pagesize int               `json:"pagesize,omitempty"`
	Type     any               `json:"type,omitempty"`
	Cookie   map[string]string `json:"-"`
	Extra    map[string]any    `json:"-"`
}

type SearchResponse = Response

type SearchComplexRequest struct {
	Keywords any               `json:"keywords,omitempty"`
	Page     int               `json:"page,omitempty"`
	Pagesize int               `json:"pagesize,omitempty"`
	Cookie   map[string]string `json:"-"`
	Extra    map[string]any    `json:"-"`
}

type SearchComplexResponse = Response

type SearchDefaultRequest struct {
	Userid  any               `json:"userid,omitempty"`
	VipType any               `json:"vip_type,omitempty"`
	Cookie  map[string]string `json:"-"`
	Extra   map[string]any    `json:"-"`
}

type SearchDefaultResponse = Response

type SearchHotRequest struct {
	Cookie map[string]string `json:"-"`
	Extra  map[string]any    `json:"-"`
}

type SearchHotResponse = Response

func (c *Client) SearchHot(ctx context.Context, req SearchHotRequest) (*SearchHotResponse, error) {
	params := structToMap(req)
	delete(params, "Cookie")
	delete(params, "Extra")
	if compat, ok := buildCompatParams("search_hot", params, req.Cookie); ok {
		params = compat
	}
	for k, v := range req.Extra {
		params[k] = v
	}
	cookie := applyCompatCookie("search_hot", req.Cookie)
	resp, err := c.Call(ctx, RouteSearchHot, Request{Params: params, Cookie: cookie})
	if err != nil {
		return nil, err
	}
	out := SearchHotResponse(*resp)
	return &out, nil
}

type SearchLyricRequest struct {
	AlbumAudioId int               `json:"album_audio_id,omitempty"`
	Hash         string            `json:"hash,omitempty"`
	Keywords     string            `json:"keywords,omitempty"`
	Man          any               `json:"man,omitempty"`
	Cookie       map[string]string `json:"-"`
	Extra        map[string]any    `json:"-"`
}

type SearchLyricResponse = Response

type SearchMixedRequest struct {
	Keyword any               `json:"keyword,omitempty"`
	Cookie  map[string]string `json:"-"`
	Extra   map[string]any    `json:"-"`
}

type SearchMixedResponse = Response

type SearchSuggestRequest struct {
	AlbumTipCount   any               `json:"albumTipCount,omitempty"`
	CorrectTipCount any               `json:"correctTipCount,omitempty"`
	Keywords        any               `json:"keywords,omitempty"`
	MusicTipCount   any               `json:"musicTipCount,omitempty"`
	MvTipCount      any               `json:"mvTipCount,omitempty"`
	Cookie          map[string]string `json:"-"`
	Extra           map[string]any    `json:"-"`
}

type SearchSuggestResponse = Response

type ServerNowRequest struct {
	Token  any               `json:"token,omitempty"`
	Userid any               `json:"userid,omitempty"`
	Cookie map[string]string `json:"-"`
	Extra  map[string]any    `json:"-"`
}

type ServerNowResponse = Response

type SheetCollectionRequest struct {
	Position any               `json:"position,omitempty"`
	Cookie   map[string]string `json:"-"`
	Extra    map[string]any    `json:"-"`
}

type SheetCollectionResponse = Response

type SheetCollectionDetailRequest struct {
	CollectionId any               `json:"collection_id,omitempty"`
	Page         any               `json:"page,omitempty"`
	Cookie       map[string]string `json:"-"`
	Extra        map[string]any    `json:"-"`
}

type SheetCollectionDetailResponse = Response

type SheetDetailRequest struct {
	Id     any               `json:"id,omitempty"`
	Source any               `json:"source,omitempty"`
	Cookie map[string]string `json:"-"`
	Extra  map[string]any    `json:"-"`
}

type SheetDetailResponse = Response

type SheetHotRequest struct {
	OpernType any               `json:"opern_type,omitempty"`
	Cookie    map[string]string `json:"-"`
	Extra     map[string]any    `json:"-"`
}

type SheetHotResponse = Response

type SheetListRequest struct {
	AlbumAudioId any               `json:"album_audio_id,omitempty"`
	OpernType    any               `json:"opern_type,omitempty"`
	Page         any               `json:"page,omitempty"`
	Pagesize     any               `json:"pagesize,omitempty"`
	Cookie       map[string]string `json:"-"`
	Extra        map[string]any    `json:"-"`
}

type SheetListResponse = Response

type SingerListRequest struct {
	Hotsize any               `json:"hotsize,omitempty"`
	Sextype any               `json:"sextype,omitempty"`
	Type    any               `json:"type,omitempty"`
	Cookie  map[string]string `json:"-"`
	Extra   map[string]any    `json:"-"`
}

type SingerListResponse = Response

type SongClimaxRequest struct {
	Hash   string            `json:"hash,omitempty"`
	Cookie map[string]string `json:"-"`
	Extra  map[string]any    `json:"-"`
}

type SongClimaxResponse = Response

type SongRankingRequest struct {
	AlbumAudioId any               `json:"album_audio_id,omitempty"`
	Cookie       map[string]string `json:"-"`
	Extra        map[string]any    `json:"-"`
}

type SongRankingResponse = Response

type SongRankingFilterRequest struct {
	AlbumAudioId any               `json:"album_audio_id,omitempty"`
	Page         any               `json:"page,omitempty"`
	Pagesize     any               `json:"pagesize,omitempty"`
	Cookie       map[string]string `json:"-"`
	Extra        map[string]any    `json:"-"`
}

type SongRankingFilterResponse = Response
